Fix some error when runing with Synopsys Caffe, but still not running
Fixed error:
1. AttributeError: 'ProposalLayer' object has no attribute 'param_str_'
2. pre_nms_topN = cfg[cfg_key].RPN_PRE_NMS_TOP_N, KeyError: '1'
3. cached dataset not removed error, which will cause the test phase accuracy calculation fail

Reference:
https://github.com/rbgirshick/py-faster-rcnn/issues/219

We need to manually remove the cached dataset in data/cache and data/VOCdevkit0712/annotations_cache when you change the train or test list in data/VOCdevkit0712/VOC0712/ImageSets/Main/

Current still facing issue
I0530 09:49:44.784348  8794 sgd_solver.cpp:144] Iteration 80, lr = 0.0005
F0530 09:50:07.775352  8794 io.cpp:87] Check failed: proto.SerializeToOstream(&output)
*** Check failure stack trace: ***
Aborted (core dumped)

Signed-off-by: Huaqi Fang <Huaqi.Fang@synopsys.com>